### ISSUE TITLE
Error on_configuration_changed

### ISSUE THREAD

**Issue by cptcanuck** [credomane/CredoTimeLapseMod#5]
After enabling the mod, I tried to load a saved map I'd just started.  Getting

"Error while running the on_configuration_changed: **CredoTimeLapseMod**/CTLM/update.lua:31 : attempt to concatenate local 'oldVersion' (a nil value)"

I'm afraid I don't know anything about digging into the code further.

![image](https://cloud.githubusercontent.com/assets/8269538/18019573/c3427446-6baa-11e6-9eda-a65bb3c8f00b.png)

Unloading the mod clears the error up.

Not using any major mods, but a bunch of minor ones.  I can list if you think it's relevant.

**Comment by credomane** [comment]
I see the issue. Give me a bit and I'll get the fix uploaded.

**Comment by credomane** [comment]
Should be fixed in https://github.com/credomane/FactorioMods_CredoTimeLapseMod/releases/tag/v0.0.8-0.13

Release is on mod portal for Factorio 0.13. I'm staying with 0.13 for a bit longer to finish my save on there. Then I'll get to working on any changes that might be needed for 0.14. Don't think there will be any but you never know.
